-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 21:12:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema army_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema army_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `army_db` DEFAULT CHARACTER SET utf8 ;
USE `army_db` ;

-- -----------------------------------------------------
-- Table `army_db`.`armies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`armies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`small_arms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`small_arms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`Generals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`Generals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `army_id` BIGINT UNSIGNED NOT NULL,
  `small_arm_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `military_badge` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Generals_armies_idx` (`army_id` ASC) VISIBLE,
  UNIQUE INDEX `military_badge_UNIQUE` (`military_badge` ASC) VISIBLE,
  INDEX `fk_Generals_small_arms1_idx` (`small_arm_id` ASC) VISIBLE,
  CONSTRAINT `fk_Generals_armies`
    FOREIGN KEY (`army_id`)
    REFERENCES `army_db`.`armies` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Generals_small_arms1`
    FOREIGN KEY (`small_arm_id`)
    REFERENCES `army_db`.`small_arms` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`Officers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`Officers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Generals_id` BIGINT UNSIGNED NOT NULL,
  `small_arms_id` BIGINT UNSIGNED NOT NULL,
  `Soldiers_id` BIGINT UNSIGNED NOT NULL,
  `Soldiers_small_arms_id` BIGINT UNSIGNED NOT NULL,
  `Soldiers_heavy_weapon_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `military_badge` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `military_badge_UNIQUE` (`military_badge` ASC) VISIBLE,
  INDEX `fk_Officers_small_arms1_idx` (`small_arms_id` ASC) VISIBLE,
  INDEX `fk_Officers_Generals1_idx` (`Generals_id` ASC) VISIBLE,
  CONSTRAINT `fk_Officers_small_arms1`
    FOREIGN KEY (`small_arms_id`)
    REFERENCES `army_db`.`small_arms` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Officers_Generals1`
    FOREIGN KEY (`Generals_id`)
    REFERENCES `army_db`.`Generals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`heavy_weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`heavy_weapons` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`Soldiers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`Soldiers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Officer_id` BIGINT UNSIGNED NOT NULL,
  `Officer_General_id` BIGINT UNSIGNED NOT NULL,
  `small_arm_id` BIGINT UNSIGNED NOT NULL,
  `heavy_weapon_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `military_badge` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `military_badge_UNIQUE` (`military_badge` ASC) VISIBLE,
  INDEX `fk_Soldiers_small_arms1_idx` (`small_arm_id` ASC) VISIBLE,
  INDEX `fk_Soldiers_heavy_weapon1_idx` (`heavy_weapon_id` ASC) VISIBLE,
  INDEX `fk_Soldiers_Officers1_idx` (`Officer_id` ASC, `Officer_General_id` ASC) VISIBLE,
  CONSTRAINT `fk_Soldiers_small_arms1`
    FOREIGN KEY (`small_arm_id`)
    REFERENCES `army_db`.`small_arms` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soldiers_heavy_weapon1`
    FOREIGN KEY (`heavy_weapon_id`)
    REFERENCES `army_db`.`heavy_weapons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soldiers_Officers1`
    FOREIGN KEY (`Officer_id` , `Officer_General_id`)
    REFERENCES `army_db`.`Officers` (`id` , `Generals_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`tanks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`tanks` (
  `number` INT NOT NULL,
  `Officer_id` BIGINT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_tanks_Officers1_idx` (`Officer_id` ASC) VISIBLE,
  CONSTRAINT `fk_tanks_Officers1`
    FOREIGN KEY (`Officer_id`)
    REFERENCES `army_db`.`Officers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`planes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Officer_id` BIGINT UNSIGNED NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_planes_Officers1_idx` (`Officer_id` ASC) VISIBLE,
  CONSTRAINT `fk_planes_Officers1`
    FOREIGN KEY (`Officer_id`)
    REFERENCES `army_db`.`Officers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`mobile_artilleries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`mobile_artilleries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Officer_id` BIGINT UNSIGNED NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_mobile_artilleries_Officers1_idx` (`Officer_id` ASC) VISIBLE,
  CONSTRAINT `fk_mobile_artilleries_Officers1`
    FOREIGN KEY (`Officer_id`)
    REFERENCES `army_db`.`Officers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`infantry_vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`infantry_vehicles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Officer_id` BIGINT UNSIGNED NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_infantry_vehicles_Officers1_idx` (`Officer_id` ASC) VISIBLE,
  CONSTRAINT `fk_infantry_vehicles_Officers1`
    FOREIGN KEY (`Officer_id`)
    REFERENCES `army_db`.`Officers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `army_db`.`heavy_artilleries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `army_db`.`heavy_artilleries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Officer_id` BIGINT UNSIGNED NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_heavy_artilleries_Officers1_idx` (`Officer_id` ASC) VISIBLE,
  CONSTRAINT `fk_heavy_artilleries_Officers1`
    FOREIGN KEY (`Officer_id`)
    REFERENCES `army_db`.`Officers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
